name: Build and Publish

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Install dependencies
              run: npm ci

            - name: Build binaries
              run: node build.js

            - name: Test binary
              run: |
                  chmod +x dist/mcp-greetings-linux-amd64
                  echo '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"test","version":"1.0.0"}}}' | timeout 5s ./dist/mcp-greetings-linux-amd64 || true

            - name: Publish to npm
              if: startsWith(github.ref, 'refs/tags/v')
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create Release
              if: startsWith(github.ref, 'refs/tags/v')
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false
